leftnav:
- identifier: dc12df75-e9ff-456d-b056-b4158029b937
  name: p1
  pageRef: /pages/p1
  weight: 10
- identifier: 1886eb79-a641-4065-b50a-5ba2b710d4b0
  name: Video page
  pageRef: /resources/whatsapp-video-2024-05-23-at-15107-pm_mp4
  weight: 20
- identifier: beb1a2e7-4ebd-4aa6-b5fb-c4aa5ec86fd1
  name: External Resource
  pageRef: /external-resources/external-resource
  weight: 30
- identifier: external-703718552-1716985152883
  name: External Link
  url: http://www.microsoft.com
  weight: 40
